### ISSUE TITLE
does the RedisSessionBackend support set customer value for the cookie‘s attribue like max-age, expires?

### ISSUE THREAD

**Issue by LvThxMax** [actix/actix-redis#10]
the cookie will be cleared  when user close the browser，does the RedisSessionBackend support set customer value for the cookie‘s attribue like max-age, expires?

**Comment by fafhrd91** [comment]
Would you provide PR.
Implementation should be similar to CookiSessionBackend from actix-web

**Comment by lvthxmax** [comment]
ok, i will try it
