### ISSUE TITLE
Supporting transactions: appropriate?

### ISSUE THREAD

**Issue by daboross** [actix/actix-redis#12]
`redis_async` leaves [redis transactions](https://redis.io/topics/transactions) as an open question.

I think this crate would be more well suited to handle transactions than `redis_async` since we have helpers like `AsyncContext::wait` which could delay all requests on a channel until a transaction is fully complete.

Do you think that that would be within the scope of this repository? If support for transactions were PRd, would it be accepted?

**Comment by JohnTitor** [comment]
Hey, we've been migrating this repository into https://github.com/actix/actix-extras. And this issue seems quite old. If you believe it's still an issue, please re-open there. Thanks!
