### ISSUE TITLE
Consider using redis-rs

### ISSUE THREAD

**Issue by gabisurita** [actix/actix-redis#15]
[Redis Rust library](https://github.com/mitsuhiko/redis-rs) recently released an async API. I think it's worth considering re-implementing this around it.
 
https://docs.rs/redis/0.9.0/redis/#async

**Comment by Dowwie** [comment]
Hi @gabisurita. Why do you think this is worth considering? What motivation is there for anyone to do this, considering actix-redis already has asyncio?

**Comment by gabisurita** [comment]
Redis-rs has many static checks for method calls and return types, as well as several libs implemented around it's API. It's as far as I know the most stable redis client implementation in Rust.

It's more a community argument than a technical one. My point is that's really nice to have one solid client implementation rather than several.
