### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fafhrd91** [actix/actix-redis#2]

**Comment by AlbanMinassian** [comment]
And write /example with Cargo.toml + src/main.rs

**Comment by ava57r** [comment]
I can help?

**Comment by fafhrd91** [comment]
Great!

**Comment by fafhrd91** [comment]
@andreevlex btw do you want to write some code not just docs? that would be helpful too!

**Comment by ava57r** [comment]
I don't mind and write the examples, but don't know what they are doing. 
Start documentation to write.

**Comment by fafhrd91** [comment]
You can write code for any package.

For example I’d like to make diesel example for actix, it mostly example from actix-web minus http part.

Here is more interesting task. Create askama integration package, something like actix-askama. TechEmpower bench uses askama templates

**Comment by fafhrd91** [comment]
But that is up to you. Documentation is great as well!

**Comment by ava57r** [comment]
@fafhrd91 #6 enough to solve this problem?

**Comment by ava57r** [comment]
if there are problems that require solutions ready to consider the possibility of their implementation

**Comment by fafhrd91** [comment]
I think it is enough for now, thanks!
