### ISSUE TITLE
Conflicts with `actix-web v1.0.0-beta.1`

### ISSUE THREAD

**Issue by JohnTitor** [actix/actix-redis#21]
`actix-redis v0.5.1` conflicts with `actix-web v1.0.0-beta.1`.

<details><summary>The log is here:</summary><div>

```
error: failed to select a version for `ring`.
    ... required by package `actix-http v0.1.1`
    ... which is depended on by `actix-web v1.0.0-beta.1`
    ... which is depended on by `foo v0.1.0`
versions that meet the requirements `^0.14.6` are: 0.14.6

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.5`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `actix-redis v0.5.1`
    ... which is depended on by `foo v0.1.0`
```

</div></details>

But it seems that master branch fixes this, so could I know when next release comes?

**Comment by eribol** [comment]
Same issue here. And i changed Cargo.toml with
actix-redis = { git = "https://github.com/actix/actix-redis.git", branch="master" }

but somehow, it does not compile new actix-redis source and gives error;
```
req: &ServiceRequest<P>,
    |                              ^ unexpected type argument
```
after this, i took https://github.com/actix/actix-redis/blob/master/src/session.rs source and overwrite to my local actix-redis session.rs file. Now it works.

**Comment by JohnTitor** [comment]
@eribol Hmm, Your solution is good but I couldn't reproduce your error on my local... It seems master has no error.

**Comment by JohnTitor** [comment]
And cc @fafhrd91, could you bump up version to fix conflicts?

**Comment by 0x8f701** [comment]
same conflict here with `actix-web 1.0.0 beta.3`

**Comment by fafhrd91** [comment]
fixed in master
