### ISSUE TITLE
support for actix_web 1.0.2

### ISSUE THREAD

**Issue by zokypesch** [actix/actix-redis#25]
hiii,

please resolved depedency library for actix web v 1.0.2

this is log error fro cargo build

failed to select a version for `ring`.
    ... required by package `actix-http v0.2.4`
    ... which is depended on by `actix-web v1.0.2`
    ... which is depended on by `payslip v0.1.0 (/Users/maulana/rust/payslip)`
versions that meet the requirements `^0.14.6` are: 0.14.6

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.5`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `actix-redis v0.5.1`
    ... which is depended on by `payslip v0.1.0 (/Users/maulana/rust/payslip)`

thanks brother,

**Comment by fafhrd91** [comment]
actix-web does not depend on payslip or cookie crates, actix-http doesn’t as well

**Comment by zokypesch** [comment]
this is my cargo.toml

[package]
name = "payslip"
version = "0.1.0"
authors = ["maulana <maulanaoktofitriadi@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"
validator = "0.8.0"
validator_derive = "0.8.0"
serde_derive="1.0.80"
serde_json="1.0"
serde="1.0"
actix-web = "1.0.2"
actix-redis = "0.5.1"

**Comment by fafhrd91** [comment]
actix-redis is not compatible with 1.0
Use it from git

**Comment by zokypesch** [comment]
do you mean use library using master ??

**Comment by fafhrd91** [comment]
Yes

**Comment by zokypesch** [comment]
ok thanks,

solved .
