### ISSUE TITLE
Docs say the users can see the session content but they can only see session key

### ISSUE THREAD

**Issue by tjamaan** [actix/actix-redis#7]
The documentation of `RedisSessionBackend` says: `whatever you write into your session is visible by the user (but not modifiable)`. The user only sees the session key and not the content as far as I can tell. Is this an error in the documentation or am I reading it wrong?

Here is the line in question:
https://github.com/actix/actix-redis/blob/7af09390ee429d3fb766d6154075e8225fa8df08/src/session.rs#L66

**Comment by 0e4ef622** [comment]
I reached the same conclusion as you and I'm wondering as well.

**Comment by fafhrd91** [comment]
this is copy/paste bug, removed
